name: test-generate-bundles

on:
  pull_request:
    branches: [main]

jobs:
  test-generate-bundles:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: "npm"
      - name: install
        run: npm ci
      - name: test generate bundles
        run: npm run test:generate:bundles
      - name: check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: Files were modified or added"
            git status
            git diff
            exit 1
          fi
